[tool.black]
line-length = 99
target-version = ['py310']
include = '\.pyi?$'
exclude = '''
/(
    \.git
  | \.venv
  | media
  | testutils
  | build
)/
'''

[tool.isort]
profile = "black"
multi_line_output = 3
include_trailing_comma = true
