[tool.black]
line-length = 99
target-version = ['py310']
include = '\.pyi?$'
exclude = '''
/(
    \.git
  | \.venv
  | \.vscode
  | tests/test_app/templates
)/
'''

[tool.isort]
profile = "black"
multi_line_output = 3
include_trailing_comma = true

[tool.pytest.ini_options]
addopts = "-ra -q"
testpaths = [
  "tests"
]
env = [
  "DJANGO_SETTINGS_MODULE = tests.test_app.settings",
]
